name: Auto CricHD Scraper

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ১ ঘণ্টা পর পর অটোমেটিক রান করবে
  workflow_dispatch: # গিটহাব থেকে ম্যানুয়ালি রান করার বাটন পাওয়ার জন্য

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper script
        run: python scraper.py

      - name: Commit and push changes if table updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update match table json data"
          file_patterns: match_table.json
